(() => {
  const EMAIL_KEY = 'e4la.auth.pendingEmail';
  const REDIRECT_KEY = 'e4la.auth.redirectTo';
  const provider = window.E4LAAuthProvider || {
    async getCurrentUser(){ return null; },
    async signIn(){ return {ok:false, code:'provider-missing'}; },
    async signUp(){ return {ok:false, code:'provider-missing'}; },
    async signOut(){ return {ok:true}; },
    async sendPasswordReset(){ return {ok:false, code:'provider-missing'}; },
    async resendVerificationEmail(){ return {ok:false, code:'provider-missing'}; }
  };
  const state = { status:'loading', user:null };
  const qs=(s,r=document)=>r.querySelector(s);
  const qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const emailOk=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim());
  const clean=v=>String(v||'').replace(/[<>]/g,'');
  const first=n=>String(n||'Client').trim().split(/\s+/)[0]||'Client';
  const initials=(n,e)=>{const s=String(n||e||'E4LA').trim();return (s.includes('@')?[s[0]]:s.split(/\s+/)).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'E4'};
  const redirectTo=()=>new URLSearchParams(location.search).get('redirect')||sessionStorage.getItem(REDIRECT_KEY)||'portal.html';
  function error(input,msg,show=true){if(!input)return false;const f=input.closest('.auth-field')||input.parentElement;const e=f&&qs('.auth-error',f);if(msg&&show){input.setAttribute('aria-invalid','true');if(e)e.textContent=msg;return false}input.removeAttribute('aria-invalid');if(e)e.textContent='';return true}
  function alert(form,msg,type='error'){const a=qs('.auth-alert',form);if(!a)return;a.textContent=msg||'';a.className=`auth-alert${msg?' is-visible':''}${type==='success'?' is-success':''}${type==='error'?' is-error':''}`}
  function load(btn,on,text){if(!btn)return;if(!btn.dataset.idle)btn.dataset.idle=btn.textContent.trim();btn.disabled=!!on;btn.textContent=on?(text||'Please wait...'):btn.dataset.idle}
  function signInHref(){const here=location.pathname.split('/').pop()||'index.html';return document.body.dataset.protected==='portal'?`sign-in.html?redirect=${encodeURIComponent(here)}`:'sign-in.html'}
  async function loadUser(){try{state.user=await provider.getCurrentUser()||null;state.status=state.user?'signed-in':'signed-out'}catch(e){state.user=null;state.status='signed-out'}renderHeader();protectPortal();if(document.body.classList.contains('auth-page')&&state.status==='signed-in'&&['sign-in.html','sign-up.html'].includes(location.pathname.split('/').pop()))location.replace('portal.html')}
  function renderHeader(){qsa('[data-auth-control]').forEach(c=>{if(state.status==='signed-in'&&state.user){const name=clean(state.user.fullName||state.user.firstName||'Client'), fn=clean(state.user.firstName||first(name)), em=clean(state.user.email||'');c.outerHTML=`<div class="auth-profile-wrap" data-auth-profile><button class="auth-profile-btn" type="button" aria-haspopup="menu" aria-expanded="false"><span class="auth-avatar">${initials(name,em)}</span><span>${fn}</span><span aria-hidden="true">⌄</span></button><div class="auth-profile-menu" role="menu"><div class="auth-profile-menu__head"><p class="auth-profile-menu__name">${name}</p><p class="auth-profile-menu__email">${em}</p></div><a role="menuitem" href="portal.html">Go to Portal</a><a role="menuitem" href="portal.html#sessions">My Sessions</a><a role="menuitem" href="portal.html#files">Shared Files</a><a role="menuitem" href="portal.html#settings">Profile & Settings</a><button role="menuitem" class="auth-signout" type="button" data-auth-signout>Sign Out</button></div></div>`}else{c.href=signInHref();c.setAttribute('aria-label','Sign in to your E4LA account');qs('.cta-neon__label',c)&&(qs('.cta-neon__label',c).textContent='Sign In');qs('.cta-neon__badge',c)?.setAttribute('hidden','')}});wireMenus()}
  function wireMenus(){qsa('[data-auth-profile]').forEach(w=>{if(w.dataset.bound)return;w.dataset.bound='1';const b=qs('.auth-profile-btn',w);const close=()=>{w.classList.remove('is-open');b.setAttribute('aria-expanded','false')};b.addEventListener('click',()=>{const open=w.classList.toggle('is-open');b.setAttribute('aria-expanded',String(open))});document.addEventListener('click',e=>{if(!w.contains(e.target))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){close();b.focus()}});qs('[data-auth-signout]',w)?.addEventListener('click',async()=>{await provider.signOut();state.user=null;state.status='signed-out';location.href='index.html#main'})})}
  function protectPortal(){if(document.body.dataset.protected==='portal'&&state.status==='signed-out'){const dest=location.pathname.split('/').pop()||'portal.html';sessionStorage.setItem(REDIRECT_KEY,dest);location.replace(`sign-in.html?redirect=${encodeURIComponent(dest)}`)}}
  function setupToggles(){qsa('[data-password-toggle]').forEach(b=>{const i=qs('#'+b.getAttribute('aria-controls'));if(!i)return;b.addEventListener('click',()=>{const show=i.type==='password';i.type=show?'text':'password';b.textContent=show?'Hide':'Show';b.setAttribute('aria-label',show?'Hide password':'Show password')})})}
  function bindValidation(form,validate){qsa('input',form).forEach(i=>{['input','change','blur'].forEach(ev=>i.addEventListener(ev,()=>{if(ev==='blur')i.dataset.touched='1';validate(form,false)}))})}
  function validateSignIn(f,force=false){const e=qs('[name=email]',f),p=qs('[name=password]',f);return error(e,emailOk(e.value)?'':'Enter a valid email address.',force||e.dataset.touched)&&error(p,p.value?'':'Enter your password.',force||p.dataset.touched)}
  function validateEmail(f,force=false){const e=qs('[name=email]',f);return error(e,emailOk(e.value)?'':'Enter a valid email address.',force||e.dataset.touched)}
  function validateSignUp(f,force=false){const n=qs('[name=fullName]',f),e=qs('[name=email]',f),p=qs('[name=password]',f),c=qs('[name=confirmPassword]',f),t=qs('[name=terms]',f),h=qs('[data-password-help]',f);if(h){h.textContent=p.value.length>=8?'Password length looks good.':'Use at least 8 characters. A real provider can enforce stronger rules.';h.classList.toggle('is-good',p.value.length>=8)}return error(n,n.value.trim().length>=2?'':'Enter your full name.',force||n.dataset.touched)&error(e,emailOk(e.value)?'':'Enter a valid email address.',force||e.dataset.touched)&error(p,p.value.length>=8?'':'Use at least 8 characters.',force||p.dataset.touched)&error(c,c.value&&c.value===p.value?'':'Passwords must match.',force||c.dataset.touched)&error(t,t.checked?'':'Accept the terms to continue.',force||t.dataset.touched)}
  function setupForms(){const si=qs('[data-auth-form="sign-in"]');if(si){bindValidation(si,validateSignIn);si.addEventListener('submit',async e=>{e.preventDefault();alert(si,'');if(!validateSignIn(si,true))return qs('[aria-invalid=true]',si)?.focus();const b=qs('[type=submit]',si);load(b,true,'Signing in...');const r=await provider.signIn(qs('[name=email]',si).value.trim(),qs('[name=password]',si).value);load(b,false);r?.ok?location.href=redirectTo():alert(si,'We couldn’t sign you in with those details. Please check your information and try again. Authentication provider configuration is still required.','error')})}const su=qs('[data-auth-form="sign-up"]');if(su){bindValidation(su,validateSignUp);su.addEventListener('submit',async e=>{e.preventDefault();alert(su,'');if(!validateSignUp(su,true))return qs('[aria-invalid=true]',su)?.focus();const b=qs('[type=submit]',su),em=qs('[name=email]',su).value.trim();load(b,true,'Creating...');const r=await provider.signUp(qs('[name=fullName]',su).value.trim(),em,qs('[name=password]',su).value);load(b,false);if(r?.ok){sessionStorage.setItem(EMAIL_KEY,em);location.href=`verify-email.html?email=${encodeURIComponent(em)}`}else alert(su,'Account creation needs an authentication provider before it can create real accounts. No password was stored.','error')})}const fp=qs('[data-auth-form="forgot"]');if(fp){bindValidation(fp,validateEmail);fp.addEventListener('submit',async e=>{e.preventDefault();alert(fp,'');if(!validateEmail(fp,true))return qs('[aria-invalid=true]',fp)?.focus();const b=qs('[type=submit]',fp);load(b,true,'Sending...');await provider.sendPasswordReset(qs('[name=email]',fp).value.trim());load(b,false);alert(fp,'If an account exists for this email, you’ll receive reset instructions shortly. Email delivery will activate when the auth provider is connected.','success')})}}
  function setupProviderButtons(){qsa('[data-provider-auth]').forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound='1';btn.addEventListener('click',()=>{const form=btn.closest('form')||document;const providerName=(btn.dataset.providerAuth||'provider').replace(/^./,c=>c.toUpperCase());alert(form,`${providerName} sign-up will activate when the authentication provider is connected. No account was created.`,`error`);});});}  function setupVerify(){const box=qs('[data-verify-email]');if(!box)return;const em=clean(new URLSearchParams(location.search).get('email')||sessionStorage.getItem(EMAIL_KEY)||'your email address');qs('[data-email-display]',box).textContent=em;const btn=qs('[data-resend]',box),status=qs('[data-resend-status]',box);let left=30,t;function tick(){btn.disabled=left>0;btn.textContent=left>0?`RESEND EMAIL (${left}s)`:'RESEND EMAIL';left>0?left--:clearInterval(t)}t=setInterval(tick,1000);tick();btn.addEventListener('click',async()=>{status.textContent='Checking email service...';const r=await provider.resendVerificationEmail(em);status.textContent=r?.ok?'Verification email sent.':'Email sending requires an authentication provider connection.';left=30;clearInterval(t);t=setInterval(tick,1000);tick()})}
  window.E4LAAuth={state,provider,loadUser};
  document.addEventListener('DOMContentLoaded',()=>{setupToggles();setupForms();setupProviderButtons();setupVerify();loadUser()});
})();


